# Exported from:        http://Pranavs-MacBook-Pro.local:5516/
# Release version:      23.3.0
# Date created:         Tue May 07 14:56:21 EDT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
